# shellcheck shell=bash

mrm_scope_apt_metadata() {
  cat <<'EOF'
title=APT sources (Ubuntu / Debian)
description=Writes /etc/apt/sources.list.d/mrm.sources (deb822)
requires_root=1
EOF
}

mrm_scope_apt_requires_root() {
  echo 1
}

mrm_scope_apt_list_path() {
  echo "/etc/apt/sources.list.d/mrm.sources"
}

mrm_scope_apt__os() {
  [[ -f /etc/os-release ]] || return 1
  # shellcheck source=/dev/null
  source /etc/os-release
  echo "${ID:-}"
}

mrm_scope_apt__codename() {
  if [[ -n "${VERSION_CODENAME:-}" ]]; then
    echo "$VERSION_CODENAME"
    return 0
  fi
  if command -v lsb_release >/dev/null 2>&1; then
    lsb_release -cs
    return 0
  fi
  return 1
}

mrm_scope_apt__write_deb822_ubuntu() {
  local uri=$1 codename=$2 out=$3
  cat >"$out" <<EOF
# Generated by mrm — do not edit manually
Types: deb
URIs: ${uri}
Suites: ${codename} ${codename}-updates ${codename}-backports
Components: main restricted universe multiverse

Types: deb
URIs: ${uri}
Suites: ${codename}-security
Components: main restricted universe multiverse
EOF
}

mrm_scope_apt__write_deb822_debian() {
  local uri=$1 codename=$2 out=$3
  cat >"$out" <<EOF
# Generated by mrm — do not edit manually
Types: deb
URIs: ${uri}
Suites: ${codename} ${codename}-updates
Components: main contrib non-free non-free-firmware

Types: deb
URIs: http://deb.debian.org/debian
Suites: ${codename}-security
Components: main contrib non-free non-free-firmware
EOF
}

# Strip trailing slash / spaces for URI comparison
mrm_scope_apt__norm_uri() {
  local u=${1//[[:space:]]/}
  u="${u%/}"
  printf '%s' "$u"
}

# Same mirror ignoring http vs https (host + path)
mrm_scope_apt__uri_same_logical() {
  local a=${1#http://}
  a=${a#https://}
  local b=${2#http://}
  b=${b#https://}
  a="${a%/}"
  b="${b%/}"
  [[ "$a" == "$b" ]]
}

# Known Ubuntu archive hosts (main + security + ports) for inference only
mrm_scope_apt__uri_is_ubuntu_official_mirror() {
  case "$(mrm_scope_apt__norm_uri "$1")" in
    http://archive.ubuntu.com/ubuntu | https://archive.ubuntu.com/ubuntu) return 0 ;;
    http://security.ubuntu.com/ubuntu | https://security.ubuntu.com/ubuntu) return 0 ;;
    http://ports.ubuntu.com/ubuntu-ports | https://ports.ubuntu.com/ubuntu-ports) return 0 ;;
  esac
  return 1
}

# Known Debian archive hosts for inference only
mrm_scope_apt__uri_is_debian_official_mirror() {
  case "$(mrm_scope_apt__norm_uri "$1")" in
    http://deb.debian.org/debian | https://deb.debian.org/debian) return 0 ;;
    http://security.debian.org/debian-security | https://security.debian.org/debian-security) return 0 ;;
    http://security.debian.org/debian | https://security.debian.org/debian) return 0 ;;
  esac
  return 1
}

# Collect http(s) mirror base URIs from one-line lists and deb822 .sources (not only mrm.sources)
mrm_scope_apt__enumerate_mirror_uris() {
  (
    shopt -s nullglob
    local f
    for f in /etc/apt/sources.list /etc/apt/sources.list.d/*.list /etc/apt/sources.list.d/*.sources; do
      [[ -f "$f" ]] || continue
      grep -hEo 'https?://[^[:space:]#\"]+' "$f" 2>/dev/null
    done | sed 's/)[.,;]*$//' | sort -u
  )
}

mrm_scope_apt_get_state() {
  local id cn_uri of_uri
  id=$(mrm_scope_apt__os) || id=""
  if [[ "$id" != "ubuntu" && "$id" != "debian" ]]; then
    echo "state=unknown"
    echo "preset="
    echo "detail=not Ubuntu/Debian (ID=${id:-?}); skipped in MVP"
    return 0
  fi
  if ! command -v yq >/dev/null 2>&1; then
    echo "state=unknown"
    echo "preset="
    echo "detail=yq required"
    return 0
  fi
  if [[ "$id" == "debian" ]]; then
    cn_uri=$(mrm_preset_yq apt chinese ".debian_uri" 2>/dev/null || true)
    of_uri=$(mrm_preset_yq apt official ".debian_uri" 2>/dev/null || true)
  else
    cn_uri=$(mrm_preset_yq apt chinese ".ubuntu_uri" 2>/dev/null || true)
    of_uri=$(mrm_preset_yq apt official ".ubuntu_uri" 2>/dev/null || true)
  fi
  [[ "$cn_uri" == "null" ]] && cn_uri=""
  [[ "$of_uri" == "null" ]] && of_uri=""

  local uris=() u nu ncn nof cn_hit=0 of_hit=0 other_hit=0
  mapfile -t uris < <(mrm_scope_apt__enumerate_mirror_uris)
  ncn=$(mrm_scope_apt__norm_uri "${cn_uri:-}")
  nof=$(mrm_scope_apt__norm_uri "${of_uri:-}")

  if [[ ${#uris[@]} -eq 0 ]]; then
    echo "state=unknown"
    echo "preset="
    echo "detail=no http(s) URIs in /etc/apt/sources.list or sources.list.d"
    return 0
  fi

  for u in "${uris[@]}"; do
    [[ -z "$u" ]] && continue
    nu=$(mrm_scope_apt__norm_uri "$u")
    if [[ -n "$ncn" ]] && { [[ "$nu" == "$ncn" ]] || mrm_scope_apt__uri_same_logical "$u" "$cn_uri"; }; then
      cn_hit=1
      continue
    fi
    if [[ -n "$nof" ]] && { [[ "$nu" == "$nof" ]] || mrm_scope_apt__uri_same_logical "$u" "$of_uri"; }; then
      of_hit=1
      continue
    fi
    if [[ "$id" == "ubuntu" ]] && mrm_scope_apt__uri_is_ubuntu_official_mirror "$nu"; then
      of_hit=1
      continue
    fi
    if [[ "$id" == "debian" ]] && mrm_scope_apt__uri_is_debian_official_mirror "$nu"; then
      of_hit=1
      continue
    fi
    other_hit=1
  done

  # Chinese mirror is the meaningful preset whenever it appears; extra official/PPA lines
  # still make state=mixed but must not blank preset (e.g. Aliyun + security.ubuntu.com + PPA).
  if ((cn_hit)); then
    local st dmsg
    if ((of_hit)) || ((other_hit)); then
      st=mixed
    else
      st=cn
    fi
    dmsg="${ncn} (sources.list / sources.list.d / mrm.sources)"
    if ((of_hit)); then
      dmsg="${dmsg}; also official archive entries (e.g. security.ubuntu.com)"
    fi
    if ((other_hit)); then
      dmsg="${dmsg}; also other third-party / PPA sources"
    fi
    echo "state=${st}"
    echo "preset=chinese"
    echo "detail=${dmsg}"
    return 0
  fi
  if ((of_hit)) && ((other_hit)); then
    echo "state=mixed"
    echo "preset="
    echo "detail=official archive with other mirrors"
    return 0
  fi
  if ((of_hit)); then
    echo "state=default"
    echo "preset=official"
    echo "detail=official archive (sources.list / sources.list.d / mrm.sources)"
    return 0
  fi

  echo "state=mixed"
  echo "preset="
  echo "detail=custom mirror(s), not mrm chinese/official: ${uris[*]}"
}

mrm_scope_apt_apply_preset() {
  local preset=$1
  mrm_is_root || {
    echo "mrm(apt): root required" >&2
    return 2
  }
  local id codename path uri tmp
  id=$(mrm_scope_apt__os) || {
    echo "mrm(apt): cannot read /etc/os-release" >&2
    return 1
  }
  if [[ "$id" != "ubuntu" && "$id" != "debian" ]]; then
    echo "mrm(apt): distro ID=${id}; MVP only supports ubuntu/debian" >&2
    return 1
  fi
  codename=$(mrm_scope_apt__codename) || {
    echo "mrm(apt): cannot resolve distro codename (VERSION_CODENAME / lsb_release)" >&2
    return 1
  }
  path=$(mrm_scope_apt_list_path)

  case "$preset" in
    chinese)
      if [[ "$id" == "debian" ]]; then
        uri=$(mrm_preset_yq apt chinese ".debian_uri") || return 1
      else
        uri=$(mrm_preset_yq apt chinese ".ubuntu_uri") || return 1
      fi
      ;;
    official)
      if [[ "$id" == "debian" ]]; then
        uri=$(mrm_preset_yq apt official ".debian_uri") || return 1
      else
        uri=$(mrm_preset_yq apt official ".ubuntu_uri") || return 1
      fi
      ;;
    *)
      echo "mrm(apt): unknown preset: ${preset}" >&2
      return 1
      ;;
  esac
  [[ "$uri" != "null" && -n "$uri" ]] || return 1

  tmp=$(mktemp)
  if [[ "$id" == "ubuntu" ]]; then
    mrm_scope_apt__write_deb822_ubuntu "$uri" "$codename" "$tmp"
  else
    mrm_scope_apt__write_deb822_debian "$uri" "$codename" "$tmp"
  fi

  if [[ -f "$path" ]] && cmp -s "$tmp" "$path" 2>/dev/null; then
    rm -f "$tmp"
    echo "already using apt/${preset}" >&2
    return 0
  fi
  [[ -f "$path" ]] && mrm_backup_file "$path" >/dev/null
  mkdir -p "$(dirname "$path")"
  mv "$tmp" "$path"
  chmod 0644 "$path"
  return 0
}

mrm_scope_apt_apply_group() {
  local group=$1 p
  p=$(mrm_group_preset "$group" "apt") || return 1
  [[ -n "$p" && "$p" != "null" ]] || return 1
  mrm_scope_apt_apply_preset "$p"
}

mrm_scope_apt_list_presets() {
  mrm_preset_table_lines apt
}

mrm_scope_apt__inferred_preset() {
  local k v pr=""
  while IFS= read -r line; do
    k=${line%%=*}
    v=${line#*=}
    [[ "$k" == preset ]] && pr="$v"
  done < <(mrm_scope_apt_get_state 2>/dev/null)
  printf '%s' "$pr"
}

# Live: fetch dists/<codename>/Release from the primary URIs line in mrm.sources (real archive path).
mrm_scope_apt__test_preset_live() {
  local preset=$1 id codename path uri url
  echo "mrm(apt-test): ${preset} matches inferred → live archive Release check" >&2
  id=$(mrm_scope_apt__os) || {
    echo "mrm(apt-test): cannot read /etc/os-release" >&2
    return 1
  }
  [[ "$id" == "ubuntu" || "$id" == "debian" ]] || {
    echo "mrm(apt-test): MVP only ubuntu/debian" >&2
    return 1
  }
  codename=$(mrm_scope_apt__codename) || {
    echo "mrm(apt-test): cannot resolve distro codename" >&2
    return 1
  }
  path=$(mrm_scope_apt_list_path)
  if [[ -f "$path" ]]; then
    uri=$(grep -m1 -E '^URIs:[[:space:]]+' "$path" | sed 's/^URIs:[[:space:]]*//;s/[[:space:]]*$//' | awk '{print $1}')
  fi
  if [[ -z "${uri:-}" ]]; then
    if [[ "$id" == "debian" ]]; then
      uri=$(mrm_preset_yq apt "$preset" '.debian_uri') || return 1
    else
      uri=$(mrm_preset_yq apt "$preset" '.ubuntu_uri') || return 1
    fi
    [[ "$uri" != "null" && -n "$uri" ]] || {
      echo "mrm(apt-test): cannot resolve URI from preset ${preset}" >&2
      return 1
    }
  fi
  uri="${uri%/}"
  url="${uri}/dists/${codename}/Release"
  mrm_http_probe "$url" "apt/${preset} live"
}

mrm_scope_apt_test_preset() {
  local preset=$1 inferred
  case "$preset" in
    chinese|official) ;;
    *)
      echo "mrm(apt): unknown preset: ${preset}" >&2
      return 1
      ;;
  esac
  inferred=$(mrm_scope_apt__inferred_preset)
  if [[ -n "$inferred" && "$inferred" == "$preset" ]]; then
    mrm_scope_apt__test_preset_live "$preset"
  else
    echo "mrm(apt-test): ${preset} is not inferred (${inferred:-none}) → HTTP probe only (.probe)" >&2
    mrm_default_test_preset_from_yaml apt "$preset"
  fi
}
